apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2  # Number of replicas (pods)
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: emaan11shaikh/my-backend-app:latest
        ports:
        - containerPort: 5000  # Port exposed by your app

