FROM node:18
WORKDIR /app

# Copy backend code
COPY Backend/package*.json ./
RUN npm install
RUN npm install -g nodemon
COPY Backend .

EXPOSE 5000
RUN npm install -g nodemon
CMD ["nodemon", "index.js"]

