apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 5000  # The port backend is listening on
      nodePort: 30008  # NodePort for accessing the service outside the cluster

